services:
  - type: web
    name: must-lms-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        value: smtp.ethereal.email
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: uj23hiueddhpna2y@ethereal.email
      - key: SMTP_PASS
        value: bUBwMXt6UWqgK4Tetd
      - key: ADMIN_EMAIL
        value: uj23hiueddhpna2y@ethereal.email

databases:
  - name: must-lms-db
    databaseName: LMS_MUST_DB_ORG
    user: postgres
    plan: free
